apiVersion: v1
kind: Pod
metadata:
  name: my-eval-deployment
  labels:
    app: my-eval-api
spec:
  containers:
  - name: my-eval-server
    image: docker/myapi:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-eval-secret
          key: db_password
  - name: my-eval-mysql
    image: datascientest/mysql-k8s:1.0.0
    ports:
    - containerPort: 3306

